<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_View More_window-top-close</name>
   <tag></tag>
   <elementGuidId>c908086d-341a-41ca-ab1b-4d0465f1499a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[7]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'window-top-close']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.window-top-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>window-top-close</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touch&quot;]/body[@class=&quot;light&quot;]/div[7]/div[@class=&quot;user-account-window manage-window-right window-spacing-less css-flex&quot;]/div[@class=&quot;item-detail-window-breadcrumbs window-size-normal visible&quot;]/div[@class=&quot;window-top-close&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
