<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>348dfd39-65cf-431a-aaf4-5d3d6afffe83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.toggle-element.style-ios.color-social-blue.state > span.input-toggle > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dynamic-table-body']/div/div/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dynamic-table-body&quot;)/div[@class=&quot;dtb-row dtr&quot;]/div[@class=&quot;dtd column-state&quot;]/label[@class=&quot;toggle-element style-ios color-social-blue state&quot;]/span[@class=&quot;input-toggle&quot;]/span[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dynamic-table-body']/div/div/label/span/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/label/span/span</value>
   </webElementXpaths>
</WebElementEntity>
