<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Open_edit</name>
   <tag></tag>
   <elementGuidId>6a3dff01-8237-4b58-83a7-cebc83caf4b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.edit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-container&quot;]/div[@class=&quot;app-body app-device-desktop&quot;]/div[@class=&quot;dashboard-layout dashboard-layout-advertiser theme-light dashboard-social-media&quot;]/div[@class=&quot;body-content&quot;]/div[@class=&quot;right-side&quot;]/div[@class=&quot;create-social-media&quot;]/div[@class=&quot;content&quot;]/div[@class=&quot;ad opened-autofill&quot;]/div[@class=&quot;ad-container-area&quot;]/div[@class=&quot;ad-step-content&quot;]/div[@class=&quot;socials-form  mobile  scroll-invisible&quot;]/div[@class=&quot;socials-view-blocks&quot;]/div[@class=&quot;mobile-template no-select&quot;]/div[@class=&quot;actions-mode&quot;]/div[@class=&quot;circle&quot;]/div[@class=&quot;edit&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[2]/div[2]/div/div[2]/div/div/div[2]/div[2]/div/div[3]/div[3]/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
