<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Join us nowPlease use only Latin charac_a65663</name>
   <tag></tag>
   <elementGuidId>07ca0b25-c809-483d-9c4c-fc726a3d6de5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auth-body-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth-body-right</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Join us nowPlease use only Latin charactersFirst nameLast nameE-mailInvalid e-mail address.CountryArmeniaPhone number ( optional )CompanyPasswordConfirm passwordI Agree toTerms and ConditionsSign upSign UpSign UpAlready registered: Sign in AdRoot</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app-container&quot;]/div[@class=&quot;app-body app-device-desktop&quot;]/div[@class=&quot;auth&quot;]/div[@class=&quot;auth-body two-col&quot;]/div[@class=&quot;auth-body-container&quot;]/div[@class=&quot;auth-body-content&quot;]/div[@class=&quot;auth-body-right&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Join us nowPlease use only Latin charactersFirst nameLast nameE-mailInvalid e-mail address.CountryArmeniaPhone number ( optional )CompanyPasswordConfirm passwordI Agree toTerms and ConditionsSign upSign UpSign UpAlready registered: Sign in AdRoot' or . = 'Join us nowPlease use only Latin charactersFirst nameLast nameE-mailInvalid e-mail address.CountryArmeniaPhone number ( optional )CompanyPasswordConfirm passwordI Agree toTerms and ConditionsSign upSign UpSign UpAlready registered: Sign in AdRoot')]</value>
   </webElementXpaths>
</WebElementEntity>
