<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__popup-close-btn</name>
   <tag></tag>
   <elementGuidId>8d328a86-8e0c-430b-be8a-d16ae613348d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.popup-close-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[10]/div/div/div/div/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-close-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-touch&quot;]/body[@class=&quot;light&quot;]/div[10]/div[@class=&quot;popup popup-huge-size media-library-modal&quot;]/div[@class=&quot;popup-container media-library-modal-container&quot;]/div[@class=&quot;popup-header with-divider with-shadow color-same-as-body&quot;]/div[@class=&quot;header-cont&quot;]/div[@class=&quot;filter-and-close-cont&quot;]/div[@class=&quot;popup-close-btn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div/div/div[3]/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
