<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Learn How To Use_popup-close-btn</name>
   <tag></tag>
   <elementGuidId>b07bc3ac-c8d8-4a4c-a437-61119a120d8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[6]/div/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.popup-close-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>popup-close-btn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;light&quot;]/div[6]/div[@class=&quot;popup popup-large-size&quot;]/div[@class=&quot;popup-container learning-content&quot;]/div[@class=&quot;popup-header with-divider with-shadow color-same-as-body&quot;]/div[@class=&quot;popup-close-btn&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[3]</value>
   </webElementXpaths>
</WebElementEntity>
